<?php
session_start(); 
/**
* Implements hook_init()
*/
function hors_init()
{ 
}

/**
* Implements hook_permission()
*/
function hors_permission()
{
  return array(
    'access hors manager' =>  array(
      'title' => t('Access Hors Manager'),
	 		'description' => t('Permission for accessing the hors manager module.'),
    ),
  );
}


/**
* Implements hook_menu()
*/
function hors_menu()
{
  $items['hors/list'] = array(
    'title' => 'Hors Manager',
    'page callback' => 'hors_list',
    'access arguments' => array('access hors manager'),
    'expanded' => TRUE,
  );
	
	$items['hors/edit'] = array(
    'title' => 'Edit Hors',
    'page callback' => 'drupal_get_form',
		'page arguments' => array('hors_edit'),
    'access arguments' => array('access hors manager'),
    'expanded' => TRUE,
  );
	
	$items['hors/updatestatus'] = array(
    'title' => 'Toggle Status',
    'page callback' => 'hors_updatestatus',
    'access arguments' => array('access hors manager'),
    'expanded' => TRUE,
  );
	
	$items['hors/delete'] = array(
    'title' => 'Delete Hors',
    'page callback' => 'hors_delete',
    'access arguments' => array('access hors manager'),
    'expanded' => TRUE,
  );
	
	$items['hors_view'] = array(
		'title' => 'Hors D\'oeuvres',
		'description' => 'Front end side view',
		'page callback' => 'hors_view',
		'access callback' => TRUE,
	);
	
	$items['hors/bookadd'] = array(
		'title' => 'Hors Book Add',
		'page callback' => 'hors_bookadd',
		'access arguments' => array('access content'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	 
	$items['hors/add'] = array(
    'title' => 'Add Hors',
    'page callback' => 'drupal_get_form',
		'page arguments' => array('hors_add'),
    'access arguments' => array('access hors manager'),
    'expanded' => TRUE,
  ); 
	return $items;
}

function hors_view()
{	
	if (isset($_SESSION['step']) && ($_SESSION['step'] >= 8))
	{
		return include('hors.php');
	}
	else if (isset($_SESSION['step']) && ($_SESSION['step'] < 8))
	{
		switch($_SESSION['step'])
		{
			case 1:
				drupal_goto('event_view');
			break;
			
			case 2:
				drupal_goto('welcome_bookview');
			break;
			
			case 3:
				drupal_goto('discount_view');
			break;
			
			case 4:
				drupal_goto('entry_view');
			break;
			
			case 5:
				drupal_goto('entry_preview');
			break;
			
			case 6:
				drupal_goto('beverage_view');
			break;
			
			case 7:
				drupal_goto('beverage_nextview');
			break;
		}
	}
	else
	{
		drupal_goto('event_view');
	}
	
}

function hors_bookadd()
{	
	if ($_POST)
	{
		$_SESSION['hors'] = $_POST;
		if (isset($_SESSION['step']))
			$_SESSION['step'] = 9;
	}
	
	if (isset($_SESSION['step']))
		drupal_goto('display_view');
	else
		drupal_goto('event_view');
}

/*
** Hors Add Form Code
*/
function hors_add($form, &$form_submit)
{
	/** ---- Hors Type Value -----
		0 = 6 Hot
		1 = Contential Bulter Service,
	**/
	
	$typeValue = array('6 Hot','Contential Bulter Service');
	
	$form['type'] = array(
		'#title' => t('Hors Type'),
		'#type' => 'select',
		'#options' => $typeValue,
		'#default_value' => $typeValue[0],
		'#description' => t('Select hors.'),
	);
	
	$form['horsName'] = array(
		'#title' => t('Hors Name'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#description' => t('Name of the hors'),
	);
	
	$form['price'] = array(
		'#title' => t('Price'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#description' => t('Price of the hors'),
	);
	
	$form['image'] = array(
		'#title' => t('Image'),
		'#type' => 'file',
	//	'#required' => TRUE,
		'#description' => t('Click "Chose File" to select an image to upload.'),
	);
	
	$form['description'] = array(
		'#title' => t('Description'),
		'#type' => 'textarea',
		'#cols' => 50,
		'#rows' => 5,
	);
	
	$status = array('False','True');
	$form['status'] = array(
		'#title' => t('Hors Status'),
		'#type' => 'select',
		'#options' => $status,
		'#default_value' => $status[1],
		'#description' => t('Select status of the current hors.'),
	);
	
	$form['orderno'] = array(
		'#title' => t('Order'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#description' => t('Enter order of the hors'),
	);
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Submit',
	);
	return $form;
}

/*
** Hors Add Code
*/
function hors_add_submit($form, &$form_state)
{
	$type 			 = $form_state['values']['type'];
	$horsName 	 = $form_state['values']['horsName'];
	$price 			 = $form_state['values']['price'];
	$image 			 = $form_state['values']['image'];
	$description = $form_state['values']['description'];
	$status 		 = $form_state['values']['status'];
	$orderno 		 = $form_state['values']['orderno'];
	
	if ($_FILES['files']['error']['image'] > 0)
  {
  	echo 'Error: ' . $_FILES['files']['error'] ['image'] . '<br>';
  }
	else
  {
		if (($_FILES['files']['type']['image'] == 'image/gif')  ||
				($_FILES['files']['type']['image'] == 'image/jpeg') || 
				($_FILES['files']['type']['image'] == 'image/jpg')  || 
				($_FILES['files']['type']['image'] == 'image/pjpeg')||
				($_FILES['files']['type']['image'] == 'image/x-png')||
				($_FILES['files']['type']['image'] == 'image/png'))
		{
			$image = drupal_get_path('module','hors').'/images/'.$_FILES['files']['name']['image'];
			move_uploaded_file($_FILES['files']['tmp_name']['image'],$image);
		}
	}
	
	$result = db_query("INSERT INTO hors(type,horsName,price,image,description,status,orderno) VALUES({$type},'{$horsName}',"
										."'{$price}','{$image}', '{$description}',{$status},{$orderno})");

	$form_state['redirect'] = 'hors/list';	
}
/*
** Delete Hors Bookin Hors Code 
*/
function hors_delete()
{
	if (isset($_GET['id']) && !empty($_GET['id']))
		$result = db_query("DELETE FROM hors where id={$_GET['id']}");
	header('Location: list');
}

/*
** Update Status of Hors Code
*/
function hors_updatestatus()
{
	if (isset($_GET['id']) && !empty($_GET['id']))
		$result = db_query("update hors set status = !status where id={$_GET['id']}");
	header('Location: list');
}

/*
** Edit Hors Form Code
*/
function hors_edit($form, &$form_submit)
{
	if (isset($_GET['id']) && !empty($_GET['id']))
	{
		$result = db_query("SELECT * FROM hors WHERE id = {$_GET['id']}");
		$row = array();

		foreach ($result as $record)
		{
			$row = (array)$record;
		}
	}
	
	/** ---- Hors Type Value -----
		0 = 6 Hot
		1 = Contential Bulter Service,
	**/
	
	$typeValue = array('6 Hot','Contential Bulter Service');
	
	$form['id'] = array(
		'#value' => $row['id'],
		'#type' => 'hidden',
	);
	
	$form['type'] = array(
		'#title' => t('Hors Type'),
		'#type' => 'select',
		'#options' => $typeValue,
		'#default_value' => $row['type'],
		'#description' => t('Select hors.'),
	);
	
	$form['horsName'] = array(
		'#title' => t('Hors Name'),
		'#type' => 'textfield',
		'#default_value' => $row['horsName'],
		'#required' => TRUE,
		'#description' => t('Name of the hors'),
	);
	
	$form['price'] = array(
		'#title' => t('Price'),
		'#type' => 'textfield',
		'#default_value' => $row['price'],
		'#required' => TRUE,
		'#description' => t('Price of the hors'),
	);
	
	$form['image'] = array(
		'#title' => t('Image'),
		'#type' => 'file',
		'#default_value' => $row['image'],
	//	'#required' => TRUE,
		'#description' => t('Click "Chose File" to select an image to upload.'),
	);
			
	$form['description'] = array(
		'#title' => t('Description'),
		'#type' => 'textarea',
		'#default_value' => $row['description'],
		'#cols' => 50,
		'#rows' => 5,
	);
	
	$status = array('False','True');
	$form['status'] = array(
		'#title' => t('Event Status'),
		'#type'  => 'select',
		'#options' => $status,
		'#default_value' => $row['status'],
		'#description' => t('Select status for the current hors.'),
	);
	
	$form['orderno'] = array(
		'#title' => t('Order'),
		'#type'  => 'textfield',
		'#default_value' => $row['orderno'],
		'#required' => TRUE,
		'#description' => t('Enter order of the hors'),
	);
	
	$form['submit'] = array(
		'#type'  => 'submit',
		'#value' => 'Submit',
	);
	return $form;
}

/*
** Edit Hors Code
*/
function hors_edit_submit($form, &$form_state)
{
	$type				 = $form_state['values']['type'];
	$horsName 	 = $form_state['values']['horsName'];
	$price 			 = $form_state['values']['price'];
	$image 			 = $form_state['values']['image'];
	$description = $form_state['values']['description'];
	$status 		 = $form_state['values']['status'];
	$orderno 		 = $form_state['values']['orderno'];
	
	$id = $form_state['values']['id'];
	
	if ($_FILES['files']['error']['image'] > 0)
  {
  	echo 'Error: ' . $_FILES['files']['error'] ['image'] . '<br>';
  }
	else
  {
		if (($_FILES['files']['type']['image'] == 'image/gif') 	||
				($_FILES['files']['type']['image'] == 'image/jpeg')	|| 
				($_FILES['files']['type']['image'] == 'image/jpg')	|| 
				($_FILES['files']['type']['image'] == 'image/pjpeg')||
				($_FILES['files']['type']['image'] == 'image/x-png')||
				($_FILES['files']['type']['image'] == 'image/png' ))
		{
			$image = drupal_get_path('module','hors').'/images/'.$_FILES['files']['name']['image'];
			move_uploaded_file($_FILES['files']['tmp_name']['image'],$image);
		}
	}
	
	$result = db_query("UPDATE hors SET type={$type}, horsName='{$horsName}', price='{$price}',image='{$image}',description="
										."'{$description}',status={$status},orderno={$orderno} WHERE id ={$id}");
	
	$form_state['redirect'] = 'hors/list';	
}

/*
** Hors List Code
*/
function hors_list($arg = 0)
{
	$result = db_query('select * from hors order by orderno');
  $rows = array();
	
	$i=0;
	foreach ($result as $record) 
	{ 
		if ($record->type == 0)
			$record->type = '6 Hot';
		else if ($record->type == 1)
			$record->type = 'Contential Bulter Service';
				
		$rows[] = array_map('check_plain', (array)$record);
		$rows[$i]['price'] = '$'.$record->price;
		
		//Make active value as standard icon
		$rows[$i]['status'] = $rows[$i]['status'] == 1 
			? l(
					theme(
						'image', 
						array(
							'path' => drupal_get_path('module','hors').'/images/active.png',
							'alt' => 'Active image', 
							'title' => 'Active',
						)
					),
					'hors/updatestatus',
					array(
						'html' => TRUE, 
						'query' => array('id' => $rows[$i]['id'])
					)
				)
				
			: l(
					theme(
						'image', 
						array(
							'path' => drupal_get_path('module','hors').'/images/inactive.png',
							'alt' => 'Inactive image',
							'title' => 'Inactive',
						)
					),
					'hors/updatestatus',
					array(
						'html' => TRUE, 
						'query' => array('id' => $rows[$i]['id'])
					)
				);
			
		$rows[$i]['image'] 	= l(
			theme(
				'image', 
				array(
					'path'   => $rows[$i]['image'], 
					'alt'    => 'Inactive image', 
					'title'  => 'Inactive',
					'height' => '50px',
					'width'  => '50px',
				 )
			),
			$rows[$i]['image'],
			array('html' => TRUE)
		);
		
		$rows[$i]['edit']		= l('Edit', 'hors/edit', array('query' => array('id' => $rows[$i]['id'])));
			
		$rows[$i]['delete'] = l('Delete', 'hors/delete', array('query' => array('id' => $rows[$i]['id'])));
	
		$i++;
	}
	
	$header = array( 
			t('Id'),
			t('Hors Type'),
			t('Hors Name'),
			t('Price'),
			t('Image'),
			t('Description'),
			t('Status'), 
			t('Order'),
			t('Date'),
			t('Edit'),
			t('Delete')
	);
  $output = theme('table', array('header' => $header, 'rows' => $rows));
  return $output .= l('Add Hors', 'hors/add');
}